Sil\Bundle\StockBundle\Domain\Entity\Location:
    type: mappedSuperclass
    table: sil_stock_location
    repositoryClass: Sil\Bundle\StockBundle\Doctrine\ORM\LocationRepository
    fields:
        name:
            type: string
        code:
            type: string(64)
            unique: true
            nullable: false
        typeValue:
            type: string(64)
            nullable: false
        managed:
            type: boolean
            nullable: false
            options:
                default: TRUE

    manyToOne:
        warehouse:
            targetEntity: Sil\Bundle\StockBundle\Domain\Entity\Warehouse
            inversedBy: locations
            joinColumn:
                name: wharehouse_id
                referencedColumnName: id

    oneToMany:
        stockUnits:
          targetEntity: Sil\Bundle\StockBundle\Domain\Entity\StockUnit
          mappedBy: location
          cascade: ["remove", "persist"]
