Sil\Bundle\StockBundle\Domain\Entity\StockItem:
    type: mappedSuperclass
    table: sil_stock_item
    repositoryClass: Sil\Bundle\StockBundle\Doctrine\ORM\StockItemRepository

    fields:
        name:
            type: string(255)
            nullable: false
        code:
            type: string(64)
            unique: true
            nullable: false

    manyToOne:
        uom:
            targetEntity: Uom
            joinColumn:
                name: uom_id
                referencedColumnName: id
                nullable: false
        outputStrategy:
            targetEntity: OutputStrategy
            joinColumn:
                name: strategy_output_id
                referencedColumnName: id
                nullable: false
