Sil\Bundle\StockBundle\Domain\Entity\StockUnit:
    type: mappedSuperclass
    table: sil_stock_unit
    repositoryClass: Sil\Bundle\StockBundle\Doctrine\ORM\StockUnitRepository
    fields:
        code:
            type: string(64)
            unique: true
            nullable: false
        qtyValue:
            type: decimal
            precision: 15
            scale: 5

    manyToOne:
        stockItem:
            targetEntity: Sil\Bundle\StockBundle\Domain\Entity\StockItemInterface
            joinColumn:
                name: stockitem_id
                referencedColumnName: id
        location:
            targetEntity: Sil\Bundle\StockBundle\Domain\Entity\Location
            inversedBy: stockUnits
            joinColumn:
                name: location_id
                referencedColumnName: id
        qtyUom:
            targetEntity: Sil\Bundle\UomBundle\Entity\Uom
            joinColumn:
                name: qty_uom_id
                referencedColumnName: id
                nullable: false
        batch:
            targetEntity: Sil\Bundle\StockBundle\Domain\Entity\BatchInterface
            joinColumn:
                name: batch_id
                referencedColumnName: id
                nullable: true

        reservationMovement:
            targetEntity: Sil\Bundle\StockBundle\Domain\Entity\Movement
            inversedBy: reservedStockUnits
            joinColumn:
                name: movement_id
                referencedColumnName: id
                nullable: true
