Sil\Bundle\StockBundle\Domain\Entity\Warehouse:
    type: mappedSuperclass
    repositoryClass: Sil\Bundle\StockBundle\Doctrine\ORM\WarehouseRepository
    
    fields:
        name:
            type: string(255)
            nullable: false
        code:
            type: string(64)
            unique: true
            nullable: false
            
    oneToMany:
        locations:
          targetEntity: Location
          mappedBy: warehouse