imports:
    - { resource: admin/sil_stock.admin.stock_item.yml }
    - { resource: admin/sil_stock.admin.movement.yml }
    - { resource: admin/sil_stock.admin.warehouse.yml }
    - { resource: admin/sil_stock.admin.location.yml }
    - { resource: admin/sil_stock.admin.uom.yml }
    - { resource: admin/sil_stock.admin.uom_type.yml }
    - { resource: admin/sil_stock.admin.stock_unit.yml }
