
services:
    sil_stock.admin.uom_type:
        class: Sil\Bundle\StockBundle\Admin\UomTypeAdmin
        arguments: [~, "%sil_stock.entity.uom_type.class%", BlastCoreBundle:CRUD]
        calls:
            - [setResourceRepository, ['@sil.stock.repository.uom_type']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.menu_label.uom_types
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
