
services:
    sil_stock.admin.warehouse:
        class: Sil\Bundle\StockBundle\Admin\WarehouseAdmin
        arguments: [~, "%sil_stock.entity.warehouse.class%", BlastCoreBundle:CRUD]
        calls:
            - [setResourceRepository, ['@sil.repository.stock_warehouse']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.menu_label.warehouses
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
