
services:
    sil_stock.admin.stock_item:
        class: Sil\Bundle\StockBundle\Admin\StockItemAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\StockItem, sil.stock.controller.stock_item]
        calls:
            - [setResourceRepository, ['@sil.stock.repository.stock_item']]
            - [setStockItemQueries, ['@sil.stock.domain_query.stock_item']]
            - [setLocationRepository, ['@sil.stock.repository.location']]
            - [ setTemplates, [{show: SilStockBundle:StockItemAdmin:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.stock_item
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix

    # sil_stock.admin.operation:
    #     class: Sil\Bundle\StockBundle\Admin\OperationAdmin
    #     arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Operation, sil.stock.controller.operation]
    #     calls:
    #         - [setOperationCodeGenerator, ['@sil.stock.code_generator.operation']]
    #         - [setMovementCodeGenerator, ['@sil.stock.code_generator.movement']]
    #         - [setLocationRepository, ['@sil.stock.repository.location']]
    #         - [setPartnerRepository, ['@sil.stock.repository.partner']]
    #         - [setResourceRepository, ['@sil.stock.repository.operation']]
    #         - [ setTemplates, [{show: SilStockBundle:OperationAdmin:show.html.twig,edit: SilStockBundle:OperationAdmin:edit.html.twig,list: SilStockBundle:OperationAdmin:list.html.twig}]]
    #     tags:
    #         -
    #             name: sonata.admin
    #             manager_type: orm
    #             group: Stock Management
    #             label: sil.stock.operation
    #             label_translator_strategy: blast.resource.sonata.label_strategy.prefix
