services:
    
    ##############
    # STOCK ITEM
    ##############
    sil_stock.admin.stock_item:
        class: Sil\Bundle\StockBundle\Admin\StockItemAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\StockItem, sil.stock.controller.stock_item]
        calls:
            - ["setResourceRepository", ['@sil.stock.repository.stock_item']]
            - ["setStockItemQueries", ['@sil.stock.domain_query.stock_item']]
            - ["setLocationRepository", ['@sil.stock.repository.location']]
            - [ setTemplates, [{show: SilStockBundle:StockItemAdmin:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.stock_item
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
    
    ##############
    # OPERATION
    ##############
    sil_stock.admin.operation:
        class: Sil\Bundle\StockBundle\Admin\OperationAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Operation, sil.stock.controller.operation]
        calls:
            - ["setOperationCodeGenerator", ['@sil.stock.code_generator.operation']]
            - ["setMovementCodeGenerator", ['@sil.stock.code_generator.movement']]
            - ["setOperationTypeRepository", ['@sil.stock.repository.operation_type']]
            - ["setLocationRepository", ['@sil.stock.repository.location']]
            - ["setResourceRepository", ['@sil.stock.repository.operation']]
            - [ setTemplates, [{show: SilStockBundle:OperationAdmin:show.html.twig,edit: SilStockBundle:OperationAdmin:edit.html.twig,list: SilStockBundle:OperationAdmin:list.html.twig}]]
            
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.operation
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
    
    ##############
    # MOVEMENT
    ##############
    sil_stock.admin.movement:
        class: Sil\Bundle\StockBundle\Admin\MovementAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Movement, BlastCoreBundle:CRUD]
        calls:
            - ["setMovementCodeGenerator", ['@sil.stock.code_generator.movement']]
            - ["setResourceRepository", ['@sil.stock.repository.movement']]
            - ["setStockItemQueries", ['@sil.stock.domain_query.stock_item']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.movement
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
            
    ##############
    # WAREHOUSE
    ##############            
    sil_stock.admin.warehouse:
        class: Sil\Bundle\StockBundle\Admin\WarehouseAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Warehouse, BlastCoreBundle:CRUD]
        calls:
            - ["setResourceRepository", ['@sil.stock.repository.warehouse']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.warehouse
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
    
    ##############
    # LOCATION
    ##############  
    sil_stock.admin.location:
        class: Sil\Bundle\StockBundle\Admin\LocationAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Location, BlastCoreBundle:CRUD]
        calls:
            - ["setResourceRepository", ['@sil.stock.repository.location']]
            - ["setStockUnitRepository", ['@sil.stock.repository.stock_unit']]
            - ["setStockItemRepository", ['@sil.stock.repository.stock_item']]
            - ["setStockItemQueries", ['@sil.stock.domain_query.stock_item']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.location
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
    
    ##############
    # UOM
    ##############  
    sil_stock.admin.uom:
        class: Sil\Bundle\StockBundle\Admin\UomAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Uom, BlastCoreBundle:CRUD]
        calls:
            - ["setResourceRepository", ['@sil.stock.repository.uom']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.uom
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
    
    ##############
    # UOM TYPE
    ##############  
    sil_stock.admin.uom_type:
        class: Sil\Bundle\StockBundle\Admin\UomTypeAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\UomType, BlastCoreBundle:CRUD]
        calls:
            - ["setResourceRepository", ['@sil.stock.repository.uom_type']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.uom_type
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
                
    
                
    ################
    # OPERATION TYPE
    ################            
    sil_stock.admin.operation_type:
        class: Sil\Bundle\StockBundle\Admin\OperationTypeAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\OperationType, BlastCoreBundle:CRUD]
        calls:
            - ["setResourceRepository", ['@sil.stock.repository.operation_type']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.operation_type
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
    
    ##############
    # STOCK UNIT
    ##############
    sil_stock.admin.stock_unit:
        class: Sil\Bundle\StockBundle\Admin\StockUnitAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\StockUnit, sil.stock.controller.stock_unit]
        calls:
            - ["setStockUnitCodeGenerator", ['@sil.stock.code_generator.stock_unit']]
            - ["setResourceRepository", ['@sil.stock.repository.stock_unit']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]
          
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.stock_unit
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
           
    