services:
    
    sil_stock.admin.stock_item:
        class: Sil\Bundle\StockBundle\Application\Admin\StockItemAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\StockItem, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.item
    
    sil_stock.admin.operation:
        class: Sil\Bundle\StockBundle\Application\Admin\OperationAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Operation, sil.stock.controller.operation]
        calls:
            - ["setOperationCodeGenerator", ['@sil.stock.code_generator.operation']]
            - ["setMovementCodeGenerator", ['@sil.stock.code_generator.movement']]
            - ["setResourceRepository", ['@sil.stock.repository.operation']]
            - [ setTemplate, [list, SilStockBundle:CRUD:list.html.twig]]
            - [ setTemplate, [edit, SilStockBundle:OperationAdmin:edit.html.twig]]
            - [ setTemplate, [show, SilStockBundle:OperationAdmin:show.html.twig]]
            
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.operation
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
    
    
    sil_stock.admin.movement:
        class: Sil\Bundle\StockBundle\Application\Admin\MovementAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Movement, BlastCoreBundle:CRUD]
        calls:
            - ["setMovementCodeGenerator", ['@sil.stock.code_generator.movement']]
            - ["setResourceRepository", ['@sil.stock.repository.movement']]
            - [ setTemplate, [list, SilStockBundle:CRUD:list.html.twig]]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.movement
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
            
                
    sil_stock.admin.warehouse:
        class: Sil\Bundle\StockBundle\Application\Admin\WarehouseAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Warehouse, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.warehouse
    
    sil_stock.admin.location:
        class: Sil\Bundle\StockBundle\Application\Admin\LocationAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Location, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.location
    
    sil_stock.admin.uom_type:
        class: Sil\Bundle\StockBundle\Application\Admin\UomTypeAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\UomType, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.uomtype
                
    
    sil_stock.admin.uom:
        class: Sil\Bundle\StockBundle\Application\Admin\UomAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Uom, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.uom
                
                
    sil_stock.admin.operation_category:
        class: Sil\Bundle\StockBundle\Application\Admin\OperationCategoryAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\OperationCategory, BlastCoreBundle:CRUD]
        calls:
            - ["setResourceRepository", ['@sil.stock.repository.operation_category']]
            - [ setTemplate, [list, SilStockBundle:CRUD:list.html.twig]]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: sil.stock.operation_category
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix