services:
    
    sil_stock.admin.item:
        class: Sil\Bundle\StockBundle\Application\Admin\StockItemAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\StockItem, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: librinfo.stock.item_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
    
    sil_stock.admin.operation:
        class: Sil\Bundle\StockBundle\Application\Admin\OperationAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Operation, BlastCoreBundle:CRUD]
        calls:
            - ["setOperationFactory", ['@sil.stock.factory.operation']]
            - ["setResourceRepository", ['@sil.stock.repository.operation']]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: librinfo.stock.operation_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
    
    
    sil_stock.admin.movement:
        class: Sil\Bundle\StockBundle\Application\Admin\MovementAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Movement, sil.stock.controller.movement]
        calls:
            - ["setMovementFactory", ['@sil.stock.factory.movement']]
            - ["setResourceRepository", ['@sil.stock.repository.movement']]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: librinfo.stock.movement_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
            
                
    sil_stock.admin.warehouse:
        class: Sil\Bundle\StockBundle\Application\Admin\WarehouseAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Warehouse, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: librinfo.stock.warehouse_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
    
    sil_stock.admin.location:
        class: Sil\Bundle\StockBundle\Application\Admin\LocationAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Location, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: librinfo.stock.location_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
    
    sil_stock.admin.uomtype:
        class: Sil\Bundle\StockBundle\Application\Admin\UomTypeAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\UomType, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: librinfo.stock.uomtype_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
    
    sil_stock.admin.uom:
        class: Sil\Bundle\StockBundle\Application\Admin\UomAdmin
        arguments: [~, Sil\Bundle\StockBundle\Domain\Entity\Uom, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Stock Management
                label: librinfo.stock.uom_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo