

parameters:
    blast:

##############
# OPERATIONS
##############

        Sil\Bundle\StockBundle\Domain\Entity\Operation:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_infos:
                            expectedAt:
                                type: sonata_type_datetime_picker
                        form_group_locations:
                            srcLocation:
                                choice_label: name
                            destLocation:
                                choice_label: name
                        
                        form_group_movements:
                            _options:
                                class: col-md-12
                            movements: 
                                type: sonata_type_collection
                                by_reference: false
                                _options:
                                    admin_code: sil_stock.admin.movement
                                    edit: inline
                                    inline: table
                    _options:
                        tabsOrder:
                            - form_tab_general
                            - form_tab_history
                            
            Sonata\AdminBundle\Show\ShowMapper:
                titleTemplate: SilStockBundle:OperationAdmin/Show:show_title.html.twig
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_infos:
                            code: ~
                            state:
                                template: SilStockBundle:OperationAdmin/Show:show_operation_state.html.twig
                            expectedAt: ~
                        show_group_locations:
                            srcLocation:
                                associated_property: name
                            destLocation:
                                associated_property: name
                        show_group_movements:
                            _options:
                                class: col-md-12
                            movements: 
                                template: SilStockBundle:OperationAdmin/Show:show_movements.html.twig
                            
                    _options:
                        tabsOrder:
                            - show_tab_general
                            - show_tab_history
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    code: ~
                    state:
                        template: SilStockBundle:OperationAdmin/Show:show_operation_state.html.twig
                    expectedAt: ~
                    srcLocation.name: ~
                    destLocation.name: ~
                    
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~


##############
# MOVEMENTS
##############

        Sil\Bundle\StockBundle\Domain\Entity\Movement:
            Sonata\AdminBundle\Form\FormMapper:
                remove:
                    createdAt: ~
                    updatedAt: ~
                add:
                    form_tab_general:
                        form_group_general:
                            stockItem:
                                choice_label: name
                            batch:
                                choice_label: code
                            qty:
                                type: Sil\Bundle\StockBundle\Application\Form\Type\UomQtyFormType
                    _options:
                        tabsOrder:
                            - form_tab_general
                            - form_tab_history
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            code: ~
                            stockItem.name: ~
                            qtyValue: ~
                            qtyUom.name: ~
                            srcLocation.name: ~
                            destLocation.name: ~
                            state:
                                template: SilStockBundle:OperationAdmin/Show:show_operation_state.html.twig
                    _options:
                        tabsOrder:
                            - form_tab_general
                            - form_tab_history
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    code: ~
                    stockItem.name: ~
                    qtyValue: ~
                    qtyUom.name: ~
                    srcLocation.name: ~
                    destLocation.name: ~
                    
                        
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code: ~
                    stockItem.name: ~
                    qtyValue: ~
                    qtyUom.name: ~
                    srcLocation.name: ~
                    destLocation.name: ~
                        
##############
# WAREHOUSES
##############

        Sil\Bundle\StockBundle\Domain\Entity\Warehouse:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            code: ~
                            name: ~
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            code: ~
                            name: ~
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    code: ~
                    name: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: 
                    code: ~
                    name: ~                 
                        
##############
# LOCATIONS
##############

        Sil\Bundle\StockBundle\Domain\Entity\Location:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            code: ~
                            name: ~
                            warehouse:
                                choice_label: name
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            code: ~
                            name: ~                               
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    code: ~
                    name: 
                        identifier: true
                    warehouse.name: ~
                     
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: 
                    code: ~
                    name: ~   


##############
# UOM TYPES
##############

        Sil\Bundle\StockBundle\Domain\Entity\UomType:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            name: ~
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            name: ~                               
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    name: 
                        identifier: true
                     
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: 
                    name: ~           
                    
##############
# UOMS
##############

        Sil\Bundle\StockBundle\Domain\Entity\Uom:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            name: ~
                            type:
                                choice_label: name
                            factor: ~
                            rounding: ~
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            name: ~
                            type.name: ~
                            factor: ~
                            rounding: ~                              
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    name: ~
                    type.name: ~
                    factor: ~
                    rounding: ~
                     
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: 
                    name: ~
                    type.name: ~
                    factor: ~
                    rounding: ~
                    
##############
# STOCK ITEMS
##############

        Sil\Bundle\StockBundle\Domain\Entity\StockItem:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            name: ~
                            code: ~
                            uom:
                                choice_label: name
                            outputStrategy:
                                choice_label: name
                            
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            name: ~
                            code: ~    
                            uom.name: ~
                            outputStrategy.name: ~
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    name: ~
                    code: ~    
                    uom.name: ~
                    outputStrategy.name: ~
                     
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: 
                    name: ~
                    code: ~    
                    uom.name: ~
                    outputStrategy.name: ~  