

parameters:
    blast:

##############
# OPERATIONS
##############

        Sil\Bundle\StockBundle\Domain\Entity\Operation:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    sil.stock.operation.form.tab.general:
                        
                        sil.stock.operation.form.group.description:
                            type:
                                choice_label: name
                                required: true
                            expectedAt:
                                type: sonata_type_datetime_picker
                                required: true
                                
                        sil.stock.operation.form.group.locations:
                            srcLocation:
                                choice_label: name
                                required: true
                            destLocation:
                                choice_label: name
                                required: true
                        
                        sil.stock.operation.form.group.movements:
                            _options:
                                class: col-md-12
                            movements:
                                label: false
                                type: sonata_type_collection
                                by_reference: false
                                _options:
                                    admin_code: sil_stock.admin.movement
                                    edit: inline
                                    inline: table
                    _options:
                        tabsOrder:
                            - sil.stock.operation.form.tab.general
                            - form_tab_history
                            
            Sonata\AdminBundle\Show\ShowMapper:
                titleTemplate: SilStockBundle:OperationAdmin/Show:show_title.html.twig
                forceTabs: true
                add:
                    sil.stock.operation.show.tab.general:
                        
                        sil.stock.operation.show.group.description:
                            type:
                                associated_property: name
                            code:
                                identifier: true
                            state:
                                template: SilStockBundle:Field:show_progress_state_field.html.twig
                            expectedAt:
                                
                        sil.stock.operation.show.group.locations:
                            srcLocation:
                                associated_property: name
                            destLocation:
                                associated_property: name
                                
                        sil.stock.operation.show.group.movements:
                            _options:
                                class: col-md-12
                            movements: 
                                template: SilStockBundle:OperationAdmin/Show:show_movements.html.twig
                            
                    _options:
                        tabsOrder:
                            - sil.stock.operation.show.tab.general
                            - show_tab_history
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove:
                    createdAt: ~
                    updatedAt: ~
                add:
                    code: ~
                    type:
                        associated_property: name
                    state:
                        template: SilStockBundle:Field:list_progress_state_field.html.twig
                    expectedAt: ~
                    srcLocation:
                        associated_property: name
                    destLocation:
                        associated_property: name
                    
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~


##################
# OPERATION TYPES
##################

        Sil\Bundle\StockBundle\Domain\Entity\OperationType:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    sil.stock.operation.form.tab.general:
                        
                        sil.stock.operation.form.group.description:
                            name:
                                required: true
                        
                    _options:
                        tabsOrder:
                            - sil.stock.operation.form.tab.general
                            - form_tab_history
                            
            Sonata\AdminBundle\Show\ShowMapper:
                titleTemplate: SilStockBundle:OperationAdmin/Show:show_title.html.twig
                forceTabs: true
                add:
                    sil.stock.operation.show.tab.general:
                        
                        sil.stock.operation.show.group.description:
                            name: ~
                            
                    _options:
                        tabsOrder:
                            - sil.stock.operation.show.tab.general
                            - show_tab_history
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove:
                    createdAt: ~
                    updatedAt: ~
                add:
                    name: ~
                    
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~

##############
# MOVEMENTS
##############

        Sil\Bundle\StockBundle\Domain\Entity\Movement:
            Sonata\AdminBundle\Form\FormMapper:
                remove:
                    createdAt: ~
                    updatedAt: ~
                add:
                    form_tab_general:
                        form_group_general:
                            stockItem:
                                choice_label: name
                            batch:
                                choice_label: code
                            qty:
                                type: Sil\Bundle\StockBundle\Application\Form\Type\UomQtyFormType
                    _options:
                        tabsOrder:
                            - form_tab_general
                            - form_tab_history
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            code: ~
                            stockItem:
                                associated_property: name
                            qty: ~
                            srcLocation:
                                associated_property: name
                            destLocation:
                                associated_property: name
                            state:
                                template: SilStockBundle:Field:show_progress_state_field.html.twig
                    _options:
                        tabsOrder:
                            - show_tab_general
                            - show_tab_history
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    code: ~
                    state:
                        template: SilStockBundle:Field:list_progress_state_field.html.twig
                    stockItem:
                        associated_property: name
                    qty: ~
                    srcLocation:
                        associated_property: name
                    destLocation:
                        associated_property: name
                    
                        
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    code: ~
                    stockItem.name: ~
                    qtyValue: ~
                    qtyUom.name: ~
                    srcLocation.name: ~
                    destLocation.name: ~
                        
##############
# WAREHOUSES
##############

        Sil\Bundle\StockBundle\Domain\Entity\Warehouse:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            code: ~
                            name: ~
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            code: ~
                            name: ~
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    code: ~
                    name: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: 
                    code: ~
                    name: ~                 
                        
##############
# LOCATIONS
##############

        Sil\Bundle\StockBundle\Domain\Entity\Location:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            code:
                                required: true
                            name: 
                                required: true
                            type:
                                type: Sil\Bundle\StockBundle\Application\Form\Type\LocationTypeFormType
                            warehouse:
                                choice_label: name
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            code: ~
                            name: ~
                            type:
                                template: SilStockBundle:Field:show_location_type_field.html.twig
                            warehouse:
                                associated_property: name
                                required: true
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    code:
                        identifier: true
                    name: ~
                    type:
                        template: SilStockBundle:Field:list_location_type_field.html.twig
                    warehouse:
                        associated_property: name
                     
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~


##############
# UOM TYPES
##############

        Sil\Bundle\StockBundle\Domain\Entity\UomType:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            name: ~
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            name: ~                               
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    name: 
                        identifier: true
                     
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: 
                    name: ~           
                    
##############
# UOMS
##############

        Sil\Bundle\StockBundle\Domain\Entity\Uom:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            name: ~
                            type:
                                choice_label: name
                            factor: ~
                            rounding: ~
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            name: ~
                            type:
                                associated_property: name
                            factor: ~
                            rounding: ~                              
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    name: ~
                    type:
                        associated_property: name
                    rounding: ~
                     
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: 
                    name: ~
                    type:
                        associated_property: name
                    factor: ~
                    rounding: ~
                    
##############
# STOCK ITEMS
##############

        Sil\Bundle\StockBundle\Domain\Entity\StockItem:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            name: ~
                            code: ~
                            uom:
                                choice_label: name
                            outputStrategy:
                                choice_label: name
                            
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            name: ~
                            code: ~    
                            uom:
                                associated_property: name
                            outputStrategy:
                                associated_property: name
                            inStockQty:
                                mapped: false
                                template: SilStockBundle:StockItemAdmin/Show:show_computed_qty.html.twig
                            reservedQty:
                                mapped: false
                                template: SilStockBundle:StockItemAdmin/Show:show_computed_qty.html.twig
                            availableQty:
                                mapped: false
                                template: SilStockBundle:StockItemAdmin/Show:show_computed_qty.html.twig
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    name: ~
                    code: ~    
                    uom:
                        associated_property: name
                    outputStrategy:
                        associated_property: name
                     
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: 
                    name: ~
                    code: ~    
                    uom.name: ~
                    outputStrategy.name: ~
            
    ##############
    # STOCK UNITS
    ##############

        Sil\Bundle\StockBundle\Domain\Entity\StockUnit:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            stockItem:
                                choice_label: name
                                attr:
                                    class: inline-block
                                    width: 50
                            batch:
                                choice_label: code
                                attr:
                                    class: inline-block
                                    width: 50
                            location: 
                                choice_label: name
                                attr:
                                    class: inline-block
                                    width: 50
                            qty:
                                type: Sil\Bundle\StockBundle\Application\Form\Type\UomQtyFormType
                                attr:
                                    class: inline-block form-inline
                                    width: 50
                             
            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            code: ~
                            stockItem:
                                associated_property: name
                            batch:
                                associated_property: code
                            location:
                                associated_property: name
                            qty: ~
                            
                            
                    _options:
                        tabsOrder:
                            - show_tab_general
                            - show_tab_history
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: 
                    code: ~
                    stockItem:
                        associated_property: name
                    batch:
                        associated_property: code
                    location:
                        associated_property: name
                    qty: ~