

parameters:
    blast:

##############
# OPERATIONS
##############

        Sil\Bundle\StockBundle\Domain\Entity\Operation:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            code: ~
                            movements: 
                                type: sonata_type_collection
                                _options:
                                    admin_code: sil_stock.admin.movement
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            code: ~
                            movements: ~
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~


##############
# MOVEMENTS
##############

        Sil\Bundle\StockBundle\Domain\Entity\Movement:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            code: ~
                            
            Sonata\AdminBundle\Show\ShowMapper:
                forceTabs: true
                add:
                    show_tab_general:
                        show_group_general:
                            code: ~
                            
            Sonata\AdminBundle\Datagrid\ListMapper:
                add: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add: ~                   
                        
                    