services:
    
    sil.stock.code_generator.movement:
        class: Sil\Bundle\StockBundle\Domain\Generator\MovementCodeGenerator
    
    sil.stock.code_generator.operation:
        class: Sil\Bundle\StockBundle\Domain\Generator\OperationCodeGenerator
    
    sil.stock.code_generator.stockunit:
        class: Sil\Bundle\StockBundle\Domain\Generator\StockUnitCodeGenerator
    
    
    sil.stock.factory.movement:
        class: Sil\Bundle\StockBundle\Domain\Factory\MovementFactory
        arguments:
            - '@sil.stock.code_generator.movement'
   
    sil.stock.factory.operation:
        class: Sil\Bundle\StockBundle\Domain\Factory\OperationFactory
        arguments:
            - '@sil.stock.code_generator.operation'
    
    sil.stock.factory.stockunit:
        class: Sil\Bundle\StockBundle\Domain\Factory\StockUnitFactory
        arguments:
            - '@sil.stock.code_generator.stockunit'
    
    ###################
    # ORM REPOSITORIES
    ###################
    
    sil.stock.repository.operation:
        class:  Sil\Bundle\StockBundle\Infrastructure\Doctrine\ORM\OperationRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Sil\Bundle\StockBundle\Domain\Entity\Operation
            
    sil.stock.repository.operation_type:
        class:  Sil\Bundle\StockBundle\Infrastructure\Doctrine\ORM\OperationTypeRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Sil\Bundle\StockBundle\Domain\Entity\OperationType
        
    sil.stock.repository.movement:
        class:  Sil\Bundle\StockBundle\Infrastructure\Doctrine\ORM\MovementRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Sil\Bundle\StockBundle\Domain\Entity\Movement
        
    sil.stock.repository.stockunit:
        class:  Sil\Bundle\StockBundle\Infrastructure\Doctrine\ORM\StockUnitRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Sil\Bundle\StockBundle\Domain\Entity\StockUnit
        
    sil.stock.repository.stockitem:
        class:  Sil\Bundle\StockBundle\Infrastructure\Doctrine\ORM\StockItemRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Sil\Bundle\StockBundle\Domain\Entity\StockItem
        
    sil.stock.repository.uomtype:
        class:  Sil\Bundle\StockBundle\Infrastructure\Doctrine\ORM\UomTypeRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Sil\Bundle\StockBundle\Domain\Entity\UomType
            
    sil.stock.repository.uom:
        class:  Sil\Bundle\StockBundle\Infrastructure\Doctrine\ORM\UomRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Sil\Bundle\StockBundle\Domain\Entity\Uom
            
    sil.stock.repository.location:
        class:  Sil\Bundle\StockBundle\Infrastructure\Doctrine\ORM\LocationRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Sil\Bundle\StockBundle\Domain\Entity\Location
            
    sil.stock.repository.location_type:
        class:  Sil\Bundle\StockBundle\Infrastructure\Doctrine\ORM\LocationTypeRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Sil\Bundle\StockBundle\Domain\Entity\LocationType
     
    ###################
    # DOMAIN SERVICE
    ###################
    
    sil.stock.domain_service.movement:
        class: Sil\Bundle\StockBundle\Domain\Service\MovementService
        arguments:
            - '@sil.stock.repository.movement'
            - '@sil.stock.repository.stockunit'
            - '@sil.stock.factory.movement'
            - '@sil.stock.factory.stockunit'
    
    sil.stock.domain_service.operation:
        class: Sil\Bundle\StockBundle\Domain\Service\OperationService
        arguments:
            - '@sil.stock.repository.operation'
            - '@sil.stock.domain_service.movement'
            - '@sil.stock.factory.operation'
     
    ###################
    # DOMAIN QUERIES
    ###################
    
    sil.stock.domain_query.stockitem:
        class: Sil\Bundle\StockBundle\Domain\Query\StockItemQueries
        arguments:
            - '@sil.stock.repository.stockunit'
    
    
   
    
    ###################
    # FORM TYPES
    ###################

    sil.stock.form.choiceloader.uomtype:
        class: Sil\Bundle\StockBundle\Application\Form\ChoiceLoader\UomTypeChoiceLoader
        arguments:
            - '@sil.stock.repository.uomtype'
    
    sil.stock.form.type.uomqty:
        class: Sil\Bundle\StockBundle\Application\Form\Type\UomQtyFormType
        tags:
            - {name: form.type, alias: form}
        arguments:
            - '@sil.stock.repository.uom'
            
    sil.stock.form.type.stockunit:
        class: Sil\Bundle\StockBundle\Application\Form\Type\StockUnitFormType
        tags:
            - {name: form.type, alias: form}
        arguments:
            - '@sil.stock.repository.location'


    ###################
    # CONTROLLERS
    ###################
    
    sil.stock.controller.operation:
        class: Sil\Bundle\StockBundle\Application\Controller\OperationCRUDController
        calls:
            - ['setContainer', ['@service_container']]
            - ['setOperationService', ['@sil.stock.domain_service.operation']]
    
    
    sil.stock.controller.stockitem:
        class: Sil\Bundle\StockBundle\Application\Controller\StockItemCRUDController
        calls:
            - ['setContainer', ['@service_container']]
      
   