Sil\Bundle\StockBundle\Domain\Entity\Bom:
    type: mappedSuperclass
    repositoryClass: Sil\Bundle\StockBundle\Doctrine\ORM\BomRepository
    fields:
        code:
            type: string(64)
            unique: true
            nullable: false
        qtyValue:
            type: decimal
            precision: 15
            scale: 5
            
    manyToOne:
        qtyUom: 
            targetEntity: Uom
            joinColumn:
                name: qty_uom_id
                referencedColumnName: id
                nullable: false
        stockItem: 
            targetEntity: StockItemInterface
            joinColumn:
                name: stockitem_id
                referencedColumnName: id
                nullable: false
                
    oneToMany:
        lines:
          targetEntity: BomLine
          mappedBy: bom
          cascade: ["remove", "persist"]
    