Sil\Bundle\StockBundle\Domain\Entity\Location:
    type: mappedSuperclass
    
    fields:
        name:
            type: string
        code:
            type: string(64)
            unique: true
            nullable: false
    
    manyToOne:
        warehouse: 
            targetEntity: Warehouse
            inversedBy: locations
            joinColumn:
                name: wharehouse_id
                referencedColumnName: id
    
    oneToMany:
        stockUnits:
          targetEntity: StockUnit
          mappedBy: location