Sil\Bundle\StockBundle\Domain\Entity\Movement:
    type: mappedSuperclass

    fields:
        code:
            type: string(64)
            unique: true
            nullable: false
        expectedAt: 
            type: datetime
            
    manyToOne:
        stockItem: 
            targetEntity: StockItemInterface
            joinColumn:
                name: stockitem_id
                referencedColumnName: id
        operation: 
            targetEntity: Operation
            inversedBy: movements
            joinColumn:
                name: operation_id
                referencedColumnName: id
        srcLocation: 
            targetEntity: Location   
            joinColumn:
                name: location_src_id
                referencedColumnName: id
        destLocation: 
            targetEntity: Location
            joinColumn:
                name: location_dest_id
                referencedColumnName: id
        batch: 
            targetEntity: BatchInterface
            joinColumn:
                name: batch_id
                referencedColumnName: id
                nullable: true
                
    oneToMany:
        reservedStockUnits:
          targetEntity: StockUnit
          mappedBy: reservationMovement
          
    embedded:
        state:
            class: ProgressState
        qty:
            class: UomQty
            
    