Sil\Bundle\StockBundle\Domain\Entity\Movement:
    type: mappedSuperclass
    repositoryClass: Sil\Bundle\StockBundle\Doctrine\ORM\MovementRepository
    fields:
        code:
            type: string(64)
            unique: true
            nullable: false
        expectedAt: 
            type: datetime
        completedAt: 
            type: datetime
            nullable: true
        qtyValue:
            type: decimal
            precision: 15
            scale: 5
        stateValue:
            type: string(64)
            
    manyToOne:
        stockItem: 
            targetEntity: StockItemInterface
            joinColumn:
                name: stockitem_id
                referencedColumnName: id
                nullable: false
        qtyUom: 
            targetEntity: Uom
            joinColumn:
                name: qty_uom_id
                referencedColumnName: id
                nullable: false
        operation: 
            targetEntity: Operation
            inversedBy: movements
            joinColumn:
                name: operation_id
                referencedColumnName: id
                nullable: false
        srcLocation: 
            targetEntity: Location   
            joinColumn:
                name: location_src_id
                referencedColumnName: id
                nullable: true
        destLocation: 
            targetEntity: Location
            joinColumn:
                name: location_dest_id
                referencedColumnName: id
                nullable: true
        batch: 
            targetEntity: BatchInterface
            joinColumn:
                name: batch_id
                referencedColumnName: id
                nullable: true
                
    oneToMany:
        reservedStockUnits:
          targetEntity: StockUnit
          mappedBy: reservationMovement
    
    