Sil\Bundle\StockBundle\Domain\Entity\OperationType:
    type: mappedSuperclass
    repositoryClass: Sil\Bundle\StockBundle\Doctrine\ORM\OperationTypeRepository
    fields:
        code:
            type: string(64)
            unique: true
            nullable: false
        name:
            type: string(64)
            unique: true
            nullable: false
    
    oneToMany:
        operations:
          targetEntity: Operation
          mappedBy: type