Sil\Bundle\StockBundle\Domain\Entity\StockUnit:
    type: mappedSuperclass
    
    fields:
        code:
            type: string(64)
            unique: true
            nullable: false
            
    manyToOne:
        stockItem: 
            targetEntity: StockItemInterface
            joinColumn:
                name: stockitem_id
                referencedColumnName: id
        location: 
            targetEntity: Location
            inversedBy: stockUnits
            joinColumn:
                name: location_id
                referencedColumnName: id
        reservationMovement: 
            targetEntity: Movement
            inversedBy: reservedStockUnits
            joinColumn:
                name: movement_id
                referencedColumnName: id
                nullable: true
                
    embedded:
        qty:
            class: UomQty
            
    