Sil\Bundle\StockBundle\Domain\Entity\Uom:
    type: mappedSuperclass
    
    fields:
        name:
            type: string(255)
            nullable: false
        factor:
            type: decimal
            precision: 15
            scale: 5
            nullable: false
        rounding:
            type: integer
            nullable: false
        active:
            type: boolean
            nullable: false
    
    manyToOne:
        type: 
            targetEntity: UomType
            joinColumn:
                name: uom_type_id
                referencedColumnName: id